[package]
name = "nust"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.27", features = ["default"] }
egui   = "0.27"
rfd    = "0.14"   # native file dialogs (Open/Save)
anyhow = "1"